Refactor to new version of the core
EasyMicroservices/Questions-Microservice pull request #9
Opened 2023-11-02 05:43 UTC by MahdiyarGHD

## Description

### Related issue(s)

### Checklist:

- [ ] It refers to an [Issue](https://github.com/EasyMicroservices/FileManager/issues).
- [ ] It fixes a bug.
- [ ] It's a new feature (non-breaking change which adds functionality)
- [ ] It's a breaking (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] CHANGELOG is updated.
- [ ] Related language label is selected.

2023-11-02 06:13 UTC, Ali-YousefiTelori requested changes

2023-11-02 06:13 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.QuestionsMicroservice.Database/Database/Contexts/QuestionContext.cs
> +        public QuestionContext(IEntityFrameworkCoreDatabaseBuilder builder)
please call base(builder)

2023-11-02 06:13 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.QuestionsMicroservice.WebApi/Program.cs
> +namespace EasyMicroservices.ContentsMicroservice.WebApi
its Question microservice

2023-11-02 06:20 UTC, AmirmohammadNemati approved these changes

2023-11-02 06:25 UTC, Mohsen-Yaghoubi approved these changes

2023-11-02 06:27 UTC, Hamed-Bagherpour approved these changes

2023-11-02 06:29 UTC, Ali-YousefiTelori approved these changes

2023-11-03 19:18 UTC, merged

2023-11-04 07:40 UTC, mahdidelzendeh72 reviewed
thanks